openapi: 3.0.0
info:
  version: 1.0.0
  title: Потоки интеграции ISF-> клиент
  description: Исходящие потоки интеграции
paths:
  /api/labControl:
    $ref: './paths/labControl.yaml'
  /api/planningResult:
    $ref: './paths/planningResult.yaml'
  /api/movement:
    $ref: './paths/movement.yaml'
components:
  schemas:
    error:
      $ref: './components/error.yaml'
    standartResponce:
      $ref: './components/standartResponce.yaml'
    workCenter:
      $ref: './components/workCenter.yaml'
