openapi: 3.0.0
info:
  version: 3.0.0
  title: Потоки интеграции ISF-> клиент  333
  description: Исходящие потоки интеграции 333
paths:
  /api/rawNomenclature:
    $ref: './paths/rawNomenclature.yaml#/pathItem'
components:
  schemas:
    error:
      $ref: './components/error.yaml'
    okResponse:
      $ref: './components/okResponse.yaml'
    product:
      $ref: './paths/rawNomenclature.yaml#/components/schemas/product'
    category:
      $ref: './paths/rawNomenclature.yaml#/components/schemas/category'
