openapi: 3.0.0
info:
  version: 3.0.0
  title: НСИ. Номенклатура
  description: |
    Мастер-системой по номенклатуре может быть Fabix или внешняя учетная система. 
    Подключение потоков зависит от потребностей производства и детализации учёта.
paths:
  /api/rawNomenclature:
    $ref: '../paths/rawNomenclature.yaml#/pathItem'
components:
  schemas:
    error:
      $ref: '../components/error.yaml'
    okResponse:
      $ref: '../components/okResponse.yaml'
   rawNomenclatureRequest: 
      $ref: '../paths/rawNomenclature.yaml#/components/schemas/rawNomenclatureRequest'   
    product:
      $ref: '../paths/rawNomenclature.yaml#/components/schemas/product'
    category:
      $ref: '../paths/rawNomenclature.yaml#/components/schemas/category'
