openapi: 3.0.0
info:
  version: 2.0.0
  title: Потоки интеграции ISF-> клиент  222
  description: Исходящие потоки интеграции 222
paths:
  /api/labControl:
    $ref: './paths/labControl.yaml#/pathItem'
  /api/planningResult:
    $ref: './paths/planningResult.yaml#/pathItem'
  /api/movement:
    $ref: './paths/movement.yaml#/pathItem'
components:
  schemas:
    error:
      $ref: './components/error.yaml'
    standartResponce:
      $ref: './components/standartResponce.yaml'
    workCenter:
      $ref: './components/workCenter.yaml'
    labControl:
      $ref: './paths/labControl.yaml#/components/schemas/labControl'
    plan:
      $ref: './paths/planningResult.yaml#/components/schemas/plan'
    movement:
      $ref: './paths/movement.yaml#/components/schemas/movement'
